M48
; DRILL file {KiCad (6.0.4)} date Wed Jan 18 22:00:42 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-01-18T22:00:42-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,NonPlated,1,8,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0390
%
G90
G05
T1
X5.9239Y-2.9035
X5.9239Y-3.1311
T2
X4.7209Y-2.8941
X4.7209Y-3.0122
T3
X5.2696Y-2.7929
X5.3096Y-2.5929
X5.3496Y-2.7929
T0
M30
